Repository shine-idle/tripf, pull requests merged in 2025-03, with the labels that each got.

#172 refactor : 프론트 헤더 수정, JwtAuthFilter 수정
  src/main/java/com/shineidle/tripf/domain/feed/controller/FeedViewController.java
  src/main/java/com/shineidle/tripf/domain/feed/service/FeedService.java
  src/main/java/com/shineidle/tripf/domain/feed/service/FeedServiceImpl.java
  src/main/java/com/shineidle/tripf/global/config/WebConfig.java
  src/main/java/com/shineidle/tripf/global/security/filter/JwtAuthFilter.java
  src/main/resources/static/js/account.js
  src/main/resources/static/js/jwt-utils.js
  src/main/resources/templates/fragments/header.html
  src/test/java/com/shineidle/tripf/domain/feed/service/FeedServiceImplTest.java
Labels: 리팩토링

#173 feat: 마이페이지 프론트 생성
  src/main/resources/templates/feed/my-page.html
Labels: 프론트

#175 refactor : 챗봇 프론트 수정, 헤더에 Ask 추가
  src/main/resources/templates/chatbot/admin.html
  src/main/resources/templates/chatbot/chat.html
  src/main/resources/templates/fragments/header.html
Labels: 코드 수정, 프론트

#176 refactor: 챗봇 프론트 수정
  src/main/resources/templates/chatbot/admin.html
  src/main/resources/templates/chatbot/chat.html
Labels: 코드 수정, 추가 기능, 프론트

#177 fix : 챗봇 관리자 인가 처리
  src/main/java/com/shineidle/tripf/domain/chatbot/controller/ChatbotViewController.java
  src/main/java/com/shineidle/tripf/global/config/WebConfig.java
  src/main/resources/templates/chatbot/chat.html
Labels: 코드 수정, 프론트

#179 refactor : 마이페이지 프론트 연동
  src/main/java/com/shineidle/tripf/domain/user/controller/AccountViewController.java
  src/main/java/com/shineidle/tripf/domain/user/controller/UserController.java
  src/main/java/com/shineidle/tripf/domain/user/controller/UserViewController.java
  src/main/java/com/shineidle/tripf/domain/user/service/UserService.java
  src/main/java/com/shineidle/tripf/domain/user/service/UserServiceImpl.java
  src/main/resources/templates/feed/my-page.html
  src/main/resources/templates/user/my-page.html
Labels: 리팩토링, 프론트

#180 refactor : 상품 조회 시 사진도 같이 조회하도록 로직 업데이트
  src/main/java/com/shineidle/tripf/domain/product/dto/ProductPhotoDto.java
  src/main/java/com/shineidle/tripf/domain/product/dto/ProductResponseDto.java
  src/main/java/com/shineidle/tripf/domain/product/repository/ProductRepository.java
  src/main/java/com/shineidle/tripf/domain/product/service/ProductServiceImpl.java
Labels: 리팩토링, 코드 수정

#181 test : Product 테스트 코드 수정
  src/test/java/com/shineidle/tripf/domain/product/service/ProductServiceImplTest.java
Labels: 테스트
