Repository shine-idle/tripf, pull requests merged in 2025-01, with the labels that each got.

#27 fix : Entity 클래스명 수정
  src/main/java/com/shineidle/tripf/cart/entity/Cart.java
  src/main/java/com/shineidle/tripf/comment/entity/CommentEntity.java
  src/main/java/com/shineidle/tripf/feed/entity/Activity.java
  src/main/java/com/shineidle/tripf/feed/entity/Days.java
  src/main/java/com/shineidle/tripf/feed/entity/Feed.java
  src/main/java/com/shineidle/tripf/notification/entity/NotificationEntity.java
Labels: 핫픽스

#31 feat : JWT를 이용한 회원가입, 로그인, 로그아웃
  src/main/java/com/shineidle/tripf/common/exception/GlobalExceptionHandler.java
  src/main/java/com/shineidle/tripf/common/message/enums/PostMessage.java
  src/main/java/com/shineidle/tripf/common/util/JwtProvider.java
  src/main/java/com/shineidle/tripf/config/SecurityConfig.java
  src/main/java/com/shineidle/tripf/config/WebConfig.java
  src/main/java/com/shineidle/tripf/config/auth/DelegatedAccessDeniedHandler.java
  src/main/java/com/shineidle/tripf/config/auth/DelegatedAuthenticationEntryPoint.java
  src/main/java/com/shineidle/tripf/config/auth/UserDetailsImpl.java
  src/main/java/com/shineidle/tripf/config/auth/UserDetailsServiceImpl.java
  src/main/java/com/shineidle/tripf/config/filter/JwtAuthFilter.java
  src/main/java/com/shineidle/tripf/user/controller/AccountController.java
  src/main/java/com/shineidle/tripf/user/controller/UserController.java
  src/main/java/com/shineidle/tripf/user/dto/UserRequestDto.java
  src/main/java/com/shineidle/tripf/user/dto/UserResponseDto.java
  src/main/java/com/shineidle/tripf/user/entity/User.java
  src/main/java/com/shineidle/tripf/user/service/UserService.java
  src/main/java/com/shineidle/tripf/user/service/UserServiceImpl.java
  src/main/java/com/shineidle/tripf/user/type/UserAuth.java
  src/main/java/com/shineidle/tripf/user/type/UserStatus.java
Labels: 새로운 기능

#32 feed 기능 일부 추가 및 예외처리 로직 추가
  src/main/java/com/shineidle/tripf/common/exception/ExceptionResponseDto.java
  src/main/java/com/shineidle/tripf/common/exception/ExceptionType.java
  src/main/java/com/shineidle/tripf/common/exception/GlobalException.java
  src/main/java/com/shineidle/tripf/common/exception/GlobalExceptionHandler.java
  src/main/java/com/shineidle/tripf/common/exception/type/FeedErrorCode.java
  src/main/java/com/shineidle/tripf/common/message/enums/PostMessage.java
  src/main/java/com/shineidle/tripf/feed/controller/FeedController.java
  src/main/java/com/shineidle/tripf/feed/dto/ActivityRequestDto.java
  src/main/java/com/shineidle/tripf/feed/dto/ActivityResponseDto.java
  src/main/java/com/shineidle/tripf/feed/dto/DaysRequestDto.java
  src/main/java/com/shineidle/tripf/feed/dto/DaysResponseDto.java
  src/main/java/com/shineidle/tripf/feed/dto/FeedRequestDto.java
  src/main/java/com/shineidle/tripf/feed/dto/FeedResponseDto.java
  src/main/java/com/shineidle/tripf/feed/entity/Activity.java
  src/main/java/com/shineidle/tripf/feed/entity/Days.java
  src/main/java/com/shineidle/tripf/feed/entity/Feed.java
  src/main/java/com/shineidle/tripf/feed/repository/ActivityRepository.java
  src/main/java/com/shineidle/tripf/feed/repository/DaysRepository.java
  src/main/java/com/shineidle/tripf/feed/repository/FeedRepository.java
  src/main/java/com/shineidle/tripf/feed/service/FeedService.java
  src/main/java/com/shineidle/tripf/feed/service/FeedServiceImpl.java
Labels: 새로운 기능, 도움 요청

#36 fix : 사용자 인증 정보가 갱신되지 않는 문제 수정
  src/main/java/com/shineidle/tripf/common/util/UserAuthorizationUtil.java
Labels: 코드 수정

#38 feat : 회원탈퇴, 권한체크 API 추가
  src/main/java/com/shineidle/tripf/common/message/enums/PostMessage.java
  src/main/java/com/shineidle/tripf/common/util/UserAuthorizationUtil.java
  src/main/java/com/shineidle/tripf/user/controller/UserController.java
  src/main/java/com/shineidle/tripf/user/entity/User.java
  src/main/java/com/shineidle/tripf/user/service/UserService.java
  src/main/java/com/shineidle/tripf/user/service/UserServiceImpl.java
  src/main/resources/application.yml
Labels: 새로운 기능, 코드 수정

#39 피드 주요 CRUD 작성 완료
  src/main/java/com/shineidle/tripf/common/exception/type/FeedErrorCode.java
  src/main/java/com/shineidle/tripf/common/message/enums/PostMessage.java
  src/main/java/com/shineidle/tripf/feed/controller/FeedController.java
  src/main/java/com/shineidle/tripf/feed/controller/HomeController.java
  src/main/java/com/shineidle/tripf/feed/dto/ActivityRequestDto.java
  src/main/java/com/shineidle/tripf/feed/dto/DaysRequestDto.java
  src/main/java/com/shineidle/tripf/feed/dto/FeedRequestDto.java
  src/main/java/com/shineidle/tripf/feed/dto/FeedResponseDto.java
  src/main/java/com/shineidle/tripf/feed/dto/RegionResponseDto.java
  src/main/java/com/shineidle/tripf/feed/entity/Activity.java
  src/main/java/com/shineidle/tripf/feed/entity/Days.java
  src/main/java/com/shineidle/tripf/feed/entity/Feed.java
  src/main/java/com/shineidle/tripf/feed/repository/ActivityRepository.java
  src/main/java/com/shineidle/tripf/feed/repository/DaysRepository.java
  src/main/java/com/shineidle/tripf/feed/repository/FeedRepository.java
  src/main/java/com/shineidle/tripf/feed/service/FeedService.java
  src/main/java/com/shineidle/tripf/feed/service/FeedServiceImpl.java
  src/main/java/com/shineidle/tripf/feed/type/nation.java
  src/main/java/com/shineidle/tripf/user/entity/User.java
Labels: 새로운 기능, 코드 수정

#41 구글지도 API, Redis 설정, 국가별조회 기능 추가
  build.gradle
  src/main/java/com/shineidle/tripf/common/exception/type/FeedErrorCode.java
  src/main/java/com/shineidle/tripf/config/RedisConfig.java
  src/main/java/com/shineidle/tripf/feed/controller/FeedController.java
  src/main/java/com/shineidle/tripf/feed/dto/RegionResponseDto.java
  src/main/java/com/shineidle/tripf/feed/entity/Feed.java
  src/main/java/com/shineidle/tripf/feed/repository/FeedRepository.java
  src/main/java/com/shineidle/tripf/feed/service/FeedService.java
  src/main/java/com/shineidle/tripf/feed/service/FeedServiceImpl.java
  src/main/java/com/shineidle/tripf/geo/dto/GeoResponseDto.java
  src/main/java/com/shineidle/tripf/geo/service/GeoService.java
  src/main/java/com/shineidle/tripf/geo/service/GeoServiceImpl.java
  src/main/resources/application.yml
Labels: 새로운 기능, 도움 요청, 코드 수정

#43 feat : 상품 기능 추가
  src/main/java/com/shineidle/tripf/common/exception/GlobalExceptionHandler.java
  src/main/java/com/shineidle/tripf/common/exception/type/ProductErrorCode.java
  src/main/java/com/shineidle/tripf/common/message/enums/PostMessage.java
  src/main/java/com/shineidle/tripf/config/WebConfig.java
  src/main/java/com/shineidle/tripf/product/ProductStatus.java
  src/main/java/com/shineidle/tripf/product/controller/AdminProductController.java
  src/main/java/com/shineidle/tripf/product/controller/ProductController.java
  src/main/java/com/shineidle/tripf/product/dto/ProductRequestDto.java
  src/main/java/com/shineidle/tripf/product/dto/ProductResponseDto.java
  src/main/java/com/shineidle/tripf/product/entity/Product.java
  src/main/java/com/shineidle/tripf/product/repository/ProductRepository.java
  src/main/java/com/shineidle/tripf/product/service/ProductService.java
  src/main/java/com/shineidle/tripf/product/service/ProductServiceImpl.java
Labels: 새로운 기능, 코드 수정

#47 댓글 CRUD 기능 추가
  src/main/java/com/shineidle/tripf/comment/controller/CommentController.java
  src/main/java/com/shineidle/tripf/comment/dto/CommentRequestDto.java
  src/main/java/com/shineidle/tripf/comment/dto/CommentResponseDto.java
  src/main/java/com/shineidle/tripf/comment/entity/Comment.java
  src/main/java/com/shineidle/tripf/comment/repository/CommentRepository.java
  src/main/java/com/shineidle/tripf/comment/service/CommentService.java
  src/main/java/com/shineidle/tripf/comment/service/CommentServiceImpl.java
  src/main/java/com/shineidle/tripf/common/exception/type/CommentErrorCode.java
  src/main/java/com/shineidle/tripf/common/util/UserAuthorizationUtil.java
  src/main/java/com/shineidle/tripf/feed/service/FeedService.java
  src/main/java/com/shineidle/tripf/feed/service/FeedServiceImpl.java
Labels: 새로운 기능

#50 Add: follow 기능 관련 파일 생성
  src/main/java/com/shineidle/tripf/follow/controller/FollowController.java
  src/main/java/com/shineidle/tripf/follow/dto/FollowRequestDto.java
  src/main/java/com/shineidle/tripf/follow/dto/FollowResponseDto.java
  src/main/java/com/shineidle/tripf/follow/entity/Follow.java
  src/main/java/com/shineidle/tripf/follow/entity/FollowPk.java
  src/main/java/com/shineidle/tripf/follow/repository/FollowRepository.java
  src/main/java/com/shineidle/tripf/follow/service/FollowService.java
  src/main/java/com/shineidle/tripf/follow/service/FollowServiceImpl.java
Labels: 새로운 기능

#49 Add: 주문 기능 추가
  src/main/java/com/shineidle/tripf/common/exception/type/OrderErrorCode.java
  src/main/java/com/shineidle/tripf/order/controller/OrderController.java
  src/main/java/com/shineidle/tripf/order/dto/OrderRequestDto.java
  src/main/java/com/shineidle/tripf/order/dto/OrderResponseDto.java
  src/main/java/com/shineidle/tripf/order/entity/Order.java
  src/main/java/com/shineidle/tripf/order/repository/OrderRepository.java
  src/main/java/com/shineidle/tripf/order/service/OrderService.java
  src/main/java/com/shineidle/tripf/order/service/OrderServiceImpl.java
  src/main/java/com/shineidle/tripf/order/type/PayStatus.java
  src/main/java/com/shineidle/tripf/orderProduct/dto/OrderProductDto.java
  src/main/java/com/shineidle/tripf/orderProduct/entity/OrderProduct.java
  src/main/java/com/shineidle/tripf/product/service/ProductService.java
  src/main/java/com/shineidle/tripf/product/service/ProductServiceImpl.java
Labels: 새로운 기능, 코드 수정

#52 메일 발송을 위한 SMTP 설정
  build.gradle
  src/main/java/com/shineidle/tripf/mail/controller/MailController.java
  src/main/java/com/shineidle/tripf/mail/service/MailService.java
  src/main/java/com/shineidle/tripf/mail/service/MailServiceImpl.java
  src/main/resources/application.yml
Labels: 새로운 기능

#54 Swagger 기능 추가
  build.gradle
  src/main/java/com/shineidle/tripf/config/SwaggerConfig.java
  src/main/java/com/shineidle/tripf/config/WebConfig.java
  src/main/resources/application.yml
Labels: 문서

#55 feat: 사진 기능 추가
  build.gradle
  src/main/java/com/shineidle/tripf/common/exception/type/PhotoErrorCode.java
  src/main/java/com/shineidle/tripf/common/message/enums/PostMessage.java
  src/main/java/com/shineidle/tripf/feed/entity/Activity.java
  src/main/java/com/shineidle/tripf/photo/config/S3Config.java
  src/main/java/com/shineidle/tripf/photo/controller/ActivityPhotoController.java
  src/main/java/com/shineidle/tripf/photo/controller/AdminProductPhotoController.java
  src/main/java/com/shineidle/tripf/photo/controller/ProductPhotoController.java
  src/main/java/com/shineidle/tripf/photo/dto/PhotoCreateRequestDto.java
  src/main/java/com/shineidle/tripf/photo/dto/PhotoCreateResponseDto.java
  src/main/java/com/shineidle/tripf/photo/entity/ActivityPhoto.java
  src/main/java/com/shineidle/tripf/photo/entity/Photo.java
  src/main/java/com/shineidle/tripf/photo/entity/ProductPhoto.java
  src/main/java/com/shineidle/tripf/photo/repository/ActivityPhotoRepository.java
  src/main/java/com/shineidle/tripf/photo/repository/PhotoRepository.java
  src/main/java/com/shineidle/tripf/photo/repository/ProductPhotoRepository.java
  src/main/java/com/shineidle/tripf/photo/service/PhotoService.java
  src/main/java/com/shineidle/tripf/photo/service/PhotoServiceImpl.java
  src/main/java/com/shineidle/tripf/photo/type/PhotoDomain.java
  src/main/java/com/shineidle/tripf/product/entity/Product.java
  src/main/resources/application.yml
Labels: 새로운 기능

#57 feat : OAuth2 소셜로그인 추가 (구글, 네이버, 카카오)
  build.gradle
  src/main/java/com/shineidle/tripf/common/util/JwtProvider.java
  src/main/java/com/shineidle/tripf/config/WebConfig.java
  src/main/java/com/shineidle/tripf/config/auth/UserDetailsServiceImpl.java
  src/main/java/com/shineidle/tripf/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/shineidle/tripf/oauth2/exception/OAuth2AuthenticationProcessingException.java
  src/main/java/com/shineidle/tripf/oauth2/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/shineidle/tripf/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/shineidle/tripf/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/shineidle/tripf/oauth2/service/OAuth2UserPrincipal.java
  src/main/java/com/shineidle/tripf/oauth2/user/OAuth2Provider.java
  src/main/java/com/shineidle/tripf/oauth2/user/OAuth2UserInfo.java
  src/main/java/com/shineidle/tripf/oauth2/user/OAuth2UserInfoFactory.java
  src/main/java/com/shineidle/tripf/oauth2/user/OAuth2UserUnlink.java
  src/main/java/com/shineidle/tripf/oauth2/user/OAuth2UserUnlinkManager.java
  src/main/java/com/shineidle/tripf/oauth2/user/RestTemplateFactory.java
  src/main/java/com/shineidle/tripf/oauth2/user/google/GoogleOAuth2UserInfo.java
  src/main/java/com/shineidle/tripf/oauth2/user/google/GoogleOAuth2UserUnlink.java
  src/main/java/com/shineidle/tripf/oauth2/user/kakao/KakaoOAuth2UserInfo.java
  src/main/java/com/shineidle/tripf/oauth2/user/kakao/KakaoOAuth2UserUnlink.java
  src/main/java/com/shineidle/tripf/oauth2/user/naver/NaverOAuth2UserInfo.java
  src/main/java/com/shineidle/tripf/oauth2/user/naver/NaverOAuth2UserUnlink.java
  src/main/java/com/shineidle/tripf/oauth2/util/CookieUtils.java
  src/main/java/com/shineidle/tripf/user/dto/UserResponseDto.java
  src/main/java/com/shineidle/tripf/user/entity/User.java
  src/main/java/com/shineidle/tripf/user/repository/UserRepository.java
  src/main/java/com/shineidle/tripf/user/service/UserServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/static/index.html
Labels: 새로운 기능, 코드 수정

#62 fix : WebConfig 코드 수정, 도커 파일 수정
  Dockerfile
  src/main/java/com/shineidle/tripf/config/WebConfig.java
  src/test/java/com/shineidle/tripf/TripfApplicationTests.java
  src/test/resources/application.yml
Labels: 코드 수정

#63 Add: follow 기능 추가
  src/main/java/com/shineidle/tripf/common/exception/type/FollowErrorCode.java
  src/main/java/com/shineidle/tripf/follow/controller/FollowController.java
  src/main/java/com/shineidle/tripf/follow/dto/FollowRequestDto.java
  src/main/java/com/shineidle/tripf/follow/dto/FollowResponseDto.java
  src/main/java/com/shineidle/tripf/follow/entity/Follow.java
  src/main/java/com/shineidle/tripf/follow/entity/FollowPk.java
  src/main/java/com/shineidle/tripf/follow/repository/FollowRepository.java
  src/main/java/com/shineidle/tripf/follow/service/FollowService.java
  src/main/java/com/shineidle/tripf/follow/service/FollowServiceImpl.java
Labels: 새로운 기능, 코드 수정

#66 fix : Swagger 관련 수정
  src/main/java/com/shineidle/tripf/config/SwaggerConfig.java
  src/main/java/com/shineidle/tripf/photo/controller/ActivityPhotoController.java
  src/main/java/com/shineidle/tripf/photo/controller/AdminProductPhotoController.java
Labels: 문서, 코드 수정

#67 Add: Like 기능 추가
  src/main/java/com/shineidle/tripf/common/exception/type/LikeErrorCode.java
  src/main/java/com/shineidle/tripf/like/controller/LikeController.java
  src/main/java/com/shineidle/tripf/like/entity/Like.java
  src/main/java/com/shineidle/tripf/like/entity/LikePk.java
  src/main/java/com/shineidle/tripf/like/repository/LikeRepository.java
  src/main/java/com/shineidle/tripf/like/service/LikeServie.java
  src/main/java/com/shineidle/tripf/like/service/LikeServieImpl.java
  src/main/java/com/shineidle/tripf/user/service/UserService.java
  src/main/java/com/shineidle/tripf/user/service/UserServiceImpl.java
Labels: 새로운 기능

#69 notification 기능 추가 (팔로우, 좋아요)
  src/main/java/com/shineidle/tripf/comment/service/CommentServiceImpl.java
  src/main/java/com/shineidle/tripf/feed/service/FeedServiceImpl.java
  src/main/java/com/shineidle/tripf/like/service/LikeServieImpl.java
  src/main/java/com/shineidle/tripf/notification/dto/NotificationResponseDto.java
  src/main/java/com/shineidle/tripf/notification/entity/Notification.java
  src/main/java/com/shineidle/tripf/notification/service/NotificationService.java
  src/main/java/com/shineidle/tripf/notification/service/NotificationServiceImpl.java
  src/main/java/com/shineidle/tripf/notification/type/NotifyType.java
  src/main/resources/application.yml
Labels: 새로운 기능, 코드 수정

#70 update : RefreshToken 관련 기능 추가
  src/main/java/com/shineidle/tripf/common/exception/type/UserErrorCode.java
  src/main/java/com/shineidle/tripf/common/util/JwtProvider.java
  src/main/java/com/shineidle/tripf/common/util/TokenType.java
  src/main/java/com/shineidle/tripf/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/shineidle/tripf/oauth2/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/shineidle/tripf/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/shineidle/tripf/oauth2/util/CookieUtils.java
  src/main/java/com/shineidle/tripf/product/service/ProductServiceImpl.java
  src/main/java/com/shineidle/tripf/user/controller/AccountController.java
  src/main/java/com/shineidle/tripf/user/dto/JwtResponseDto.java
  src/main/java/com/shineidle/tripf/user/entity/RefreshToken.java
  src/main/java/com/shineidle/tripf/user/repository/RefreshTokenRepository.java
  src/main/java/com/shineidle/tripf/user/service/RefreshTokenService.java
  src/main/java/com/shineidle/tripf/user/service/RefreshTokenServiceImpl.java
  src/main/java/com/shineidle/tripf/user/service/UserService.java
  src/main/java/com/shineidle/tripf/user/service/UserServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/static/index.html
Labels: 코드 수정, 추가 기능

#71 update : 소셜 로그인 unlink 컨트롤러 추가
  src/main/java/com/shineidle/tripf/oauth2/controller/OAuth2UnlinkController.java
  src/main/java/com/shineidle/tripf/user/service/RefreshTokenService.java
  src/main/java/com/shineidle/tripf/user/service/RefreshTokenServiceImpl.java
Labels: 추가 기능

#74 update : mail 기능 수정 및 추가
  build.gradle
  src/main/java/com/shineidle/tripf/like/controller/LikeController.java
  src/main/java/com/shineidle/tripf/like/dto/FeedLikeDto.java
  src/main/java/com/shineidle/tripf/like/repository/LikeRepository.java
  src/main/java/com/shineidle/tripf/like/service/LikeService.java
  src/main/java/com/shineidle/tripf/like/service/LikeServiceImpl.java
  src/main/java/com/shineidle/tripf/like/service/LikeServie.java
  src/main/java/com/shineidle/tripf/mail/controller/MailController.java
  src/main/java/com/shineidle/tripf/mail/service/MailService.java
  src/main/java/com/shineidle/tripf/mail/service/MailServiceImpl.java
  src/main/java/com/shineidle/tripf/photo/service/PhotoService.java
  src/main/java/com/shineidle/tripf/photo/service/PhotoServiceImpl.java
  src/main/java/com/shineidle/tripf/user/repository/UserRepository.java
  src/main/java/com/shineidle/tripf/user/service/UserService.java
  src/main/java/com/shineidle/tripf/user/service/UserServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/static/images/image-1.png
  src/main/resources/static/images/image-2.png
  src/main/resources/static/images/image-3.png
  src/main/resources/static/images/image-4.png
  src/main/resources/static/images/image-5.png
  src/main/resources/static/images/image-6.png
  src/main/resources/static/images/image-7.png
  src/main/resources/static/images/image-8.png
  src/main/resources/static/images/image-9.png
  src/main/resources/templates/top-feeds-email.html
Labels: 코드 수정, 추가 기능

#75 update : 탈퇴된 회원에 대한 예외처리 추가
  src/main/java/com/shineidle/tripf/common/exception/type/UserErrorCode.java
  src/main/java/com/shineidle/tripf/user/controller/UserController.java
  src/main/java/com/shineidle/tripf/user/service/UserServiceImpl.java
Labels: 코드 수정

#76 fix: follow 코드 수정
  src/main/java/com/shineidle/tripf/follow/entity/Follow.java
  src/main/java/com/shineidle/tripf/follow/entity/FollowPk.java
  src/main/java/com/shineidle/tripf/follow/repository/FollowRepository.java
  src/main/java/com/shineidle/tripf/follow/service/FollowServiceImpl.java
Labels: 코드 수정

#77 update : mail 이미지 없을 시 기본 이미지 포함하여 발송되도록 수정
  src/main/java/com/shineidle/tripf/like/dto/FeedLikeDto.java
  src/main/java/com/shineidle/tripf/mail/service/MailServiceImpl.java
  src/main/resources/templates/top-feeds-email.html
Labels: 코드 수정

#78 Create README.md
  README.md
Labels: 문서, 도움 요청

#79 add : home(메인페이지) 조회 기능 추가
  src/main/java/com/shineidle/tripf/feed/controller/HomeController.java
  src/main/java/com/shineidle/tripf/feed/dto/HomeResponseDto.java
  src/main/java/com/shineidle/tripf/feed/repository/FeedRepository.java
  src/main/java/com/shineidle/tripf/feed/service/FeedService.java
  src/main/java/com/shineidle/tripf/feed/service/FeedServiceImpl.java
Labels: 새로운 기능, 코드 수정

#94 update : User Redis 캐싱 (Cache Aside 패턴)
  src/main/java/com/shineidle/tripf/common/util/RedisUtils.java
  src/main/java/com/shineidle/tripf/config/RedisConfig.java
  src/main/java/com/shineidle/tripf/config/auth/UserDetailsServiceImpl.java
  src/main/java/com/shineidle/tripf/user/service/UserServiceImpl.java
Labels: 코드 수정, 추가 기능

#96 CI/CD 설정
  .github/workflows/ec2-docker.yml
  Dockerfile
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: 도움 요청, 추가 기능

#97 fix: 장바구니 @Transactional 추가
  src/main/java/com/shineidle/tripf/cart/service/CartServiceImpl.java
Labels: 리펙토링

#98 add : thymeleaf 적용 프론트 추가
  build.gradle
  src/main/java/com/shineidle/tripf/feed/controller/FeedViewController.java
  src/main/java/com/shineidle/tripf/feed/controller/HomeViewController.java
  src/main/java/com/shineidle/tripf/feed/dto/HomeResponseDto.java
  src/main/java/com/shineidle/tripf/feed/repository/FeedRepository.java
  src/main/java/com/shineidle/tripf/feed/service/FeedService.java
  src/main/java/com/shineidle/tripf/feed/service/FeedServiceImpl.java
  src/main/java/com/shineidle/tripf/follow/service/FollowServiceImpl.java
  src/main/java/com/shineidle/tripf/user/controller/AccountViewController.java
  src/main/resources/application.yml
  src/main/resources/templates/feed/activity-create.html
  src/main/resources/templates/feed/countries.html
  src/main/resources/templates/feed/country-feeds.html
  src/main/resources/templates/feed/day-create.html
  src/main/resources/templates/feed/detail.html
  src/main/resources/templates/feed/edit.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/home-guest.html
  src/main/resources/templates/home-logged-in.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/default_layout.html
  src/main/resources/templates/mail/top-feeds-email.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/signup.html
Labels: 새로운 기능, 도움 요청, 추가 기능, 프론트

#99 Fix: order 코드수정
  src/main/java/com/shineidle/tripf/order/dto/OrderResponseDto.java
  src/main/java/com/shineidle/tripf/order/entity/Order.java
  src/main/java/com/shineidle/tripf/order/service/OrderServiceImpl.java
  src/main/java/com/shineidle/tripf/orderProduct/entity/OrderProduct.java
Labels: 코드 수정

#100 feat : 채팅 기능 추가
  build.gradle
  src/main/java/com/shineidle/tripf/chat/controller/ChatController.java
  src/main/java/com/shineidle/tripf/chat/controller/ChatRoomController.java
  src/main/java/com/shineidle/tripf/chat/dto/ChatMessageRequestDto.java
  src/main/java/com/shineidle/tripf/chat/dto/ChatMessageResponseDto.java
  src/main/java/com/shineidle/tripf/chat/dto/ChatRoomRequestDto.java
  src/main/java/com/shineidle/tripf/chat/dto/ChatRoomResponseDto.java
  src/main/java/com/shineidle/tripf/chat/entity/ChatMessage.java
  src/main/java/com/shineidle/tripf/chat/entity/ChatRoom.java
  src/main/java/com/shineidle/tripf/chat/repository/ChatMessageRepository.java
  src/main/java/com/shineidle/tripf/chat/repository/ChatRoomRepository.java
  src/main/java/com/shineidle/tripf/chat/service/ChatMessageService.java
  src/main/java/com/shineidle/tripf/chat/service/ChatMessageServiceImpl.java
  src/main/java/com/shineidle/tripf/chat/service/ChatRoomService.java
  src/main/java/com/shineidle/tripf/chat/service/ChatRoomServiceImpl.java
  src/main/java/com/shineidle/tripf/common/util/JwtProvider.java
  src/main/java/com/shineidle/tripf/common/util/chat/StompHandler.java
  src/main/java/com/shineidle/tripf/common/util/chat/WebSocketSessionManager.java
  src/main/java/com/shineidle/tripf/config/WebConfig.java
  src/main/java/com/shineidle/tripf/config/WebSocketConfig.java
  src/main/java/com/shineidle/tripf/config/interceptor/JwtHandshakeInterceptor.java
  src/main/resources/application.yml
  src/main/resources/static/chat.html
  src/main/resources/static/css/main.css
  src/main/resources/static/js/app.js
  src/main/resources/static/social-login.html
Labels: 새로운 기능, 코드 수정

#101 add 프론트 추가 개발
  src/main/java/com/shineidle/tripf/cart/controller/CartViewController.java
  src/main/java/com/shineidle/tripf/config/WebConfig.java
  src/main/java/com/shineidle/tripf/feed/controller/FeedViewController.java
  src/main/java/com/shineidle/tripf/feed/controller/HomeViewController.java
  src/main/java/com/shineidle/tripf/feed/service/FeedServiceImpl.java
  src/main/java/com/shineidle/tripf/mail/service/MailServiceImpl.java
  src/main/java/com/shineidle/tripf/product/controller/AdminProductViewController.java
  src/main/java/com/shineidle/tripf/product/controller/ProductViewController.java
  src/main/java/com/shineidle/tripf/user/controller/AccountViewController.java
  src/main/java/com/shineidle/tripf/user/controller/UserViewController.java
  src/main/resources/static/images/countries/china.gif
  src/main/resources/static/images/countries/france.gif
  src/main/resources/static/images/countries/japan.gif
  src/main/resources/static/images/countries/korea.jpg
  src/main/resources/static/images/countries/spain.gif
  src/main/resources/static/images/countries/uk.gif
  src/main/resources/static/images/countries/usa.gif
  src/main/resources/static/images/countries/vietnam.gif
  src/main/resources/static/images/mail/image-1.png
  src/main/resources/static/images/mail/image-2.png
  src/main/resources/static/images/mail/image-3.png
  src/main/resources/static/images/mail/image-4.png
  src/main/resources/static/images/mail/image-5.png
  src/main/resources/static/images/mail/image-6.png
  src/main/resources/static/images/mail/image-7.png
  src/main/resources/static/images/mail/image-8.png
  src/main/resources/static/images/mail/image-9.png
  src/main/resources/templates/cart/cartList.html
  src/main/resources/templates/feed/activity-create.html
  src/main/resources/templates/feed/countries.html
  src/main/resources/templates/feed/country-feeds.html
  src/main/resources/templates/feed/create.html
  src/main/resources/templates/feed/detail.html
  src/main/resources/templates/feed/edit.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/home/home-guest.html
  src/main/resources/templates/home/home-logged-in.html
  src/main/resources/templates/product/adminProductForm.html
  src/main/resources/templates/product/productDetail.html
  src/main/resources/templates/product/productList.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/logout.html
Labels: 프론트

#102 update : 피드 Lock 생성, 본인 피드 조회 추가, 프론트 수정
  build.gradle
  src/main/java/com/shineidle/tripf/common/exception/type/FeedErrorCode.java
  src/main/java/com/shineidle/tripf/common/exception/type/LockErrorCode.java
  src/main/java/com/shineidle/tripf/config/RedisConfig.java
  src/main/java/com/shineidle/tripf/feed/controller/FeedController.java
  src/main/java/com/shineidle/tripf/feed/controller/FeedViewController.java
  src/main/java/com/shineidle/tripf/feed/dto/FeedResponseDto.java
  src/main/java/com/shineidle/tripf/feed/dto/MyFeedResponseDto.java
  src/main/java/com/shineidle/tripf/feed/repository/FeedRepository.java
  src/main/java/com/shineidle/tripf/feed/service/FeedService.java
  src/main/java/com/shineidle/tripf/feed/service/FeedServiceImpl.java
  src/main/resources/templates/feed/activity-create.html
  src/main/resources/templates/feed/countries.html
  src/main/resources/templates/feed/country-feeds.html
  src/main/resources/templates/feed/create.html
  src/main/resources/templates/feed/day-create.html
  src/main/resources/templates/feed/detail.html
  src/main/resources/templates/feed/my-feeds.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/home/home-guest.html
  src/main/resources/templates/home/home-logged-in.html
  src/main/resources/templates/product/adminProductForm.html
  src/main/resources/templates/product/productDetail.html
  src/main/resources/templates/product/productList.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/signup.html
Labels: 코드 수정, 추가 기능, 프론트

#103 update : 유저 관련 프론트 작업
  src/main/java/com/shineidle/tripf/user/controller/AccountViewController.java
  src/main/resources/templates/user/signup-success.html
  src/main/resources/templates/user/signup.html
Labels: 프론트

#104 update : 피드 사진 반환하도록 수정
  src/main/java/com/shineidle/tripf/feed/controller/FeedViewController.java
  src/main/java/com/shineidle/tripf/feed/dto/ActivityResponseDto.java
  src/main/java/com/shineidle/tripf/feed/dto/FeedResponseDto.java
  src/main/java/com/shineidle/tripf/feed/dto/MyFeedResponseDto.java
  src/main/java/com/shineidle/tripf/feed/dto/RegionResponseDto.java
  src/main/java/com/shineidle/tripf/feed/entity/Activity.java
  src/main/java/com/shineidle/tripf/feed/repository/DaysRepository.java
  src/main/java/com/shineidle/tripf/feed/service/FeedService.java
  src/main/java/com/shineidle/tripf/feed/service/FeedServiceImpl.java
  src/main/resources/static/images/default.jpg
  src/main/resources/templates/feed/countries.html
  src/main/resources/templates/feed/country-feeds.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/home/home-guest.html
  src/main/resources/templates/home/home-logged-in.html
Labels: 코드 수정, 추가 기능, 프론트

#107 update : 댓글 Redis 분산락 적용
  src/main/java/com/shineidle/tripf/comment/service/CommentServiceImpl.java
Labels: 코드 수정, 추가 기능

#108 add : Feature/front/comment 피드 댓글 프론트 생성
  src/main/java/com/shineidle/tripf/feed/controller/FeedViewController.java
  src/main/resources/templates/feed/create.html
  src/main/resources/templates/feed/detail.html
Labels: 코드 수정, 프론트

#109 add : notification 프론트 추가
  src/main/java/com/shineidle/tripf/notification/controller/NotificationViewController.java
  src/main/resources/templates/fragments/header.html
Labels: 코드 수정, 추가 기능, 프론트

#110 update : 로그인, 피드 프론트 작업
  src/main/java/com/shineidle/tripf/common/util/ApplicationContextProvider.java
  src/main/java/com/shineidle/tripf/common/util/JwtProvider.java
  src/main/java/com/shineidle/tripf/common/util/UserAuthorizationUtil.java
  src/main/java/com/shineidle/tripf/config/WebConfig.java
  src/main/java/com/shineidle/tripf/feed/controller/FeedController.java
  src/main/java/com/shineidle/tripf/feed/controller/FeedViewController.java
  src/main/java/com/shineidle/tripf/feed/controller/HomeViewController.java
  src/main/java/com/shineidle/tripf/feed/service/FeedService.java
  src/main/java/com/shineidle/tripf/feed/service/FeedServiceImpl.java
  src/main/java/com/shineidle/tripf/user/controller/AccountController.java
  src/main/java/com/shineidle/tripf/user/controller/AccountViewController.java
  src/main/java/com/shineidle/tripf/user/service/UserService.java
  src/main/java/com/shineidle/tripf/user/service/UserServiceImpl.java
  src/main/resources/templates/feed/create.html
  src/test/resources/application.yml
Labels: 코드 수정, 프론트
