Repository shine-idle/tripf, pull requests merged in 2025-02, with the labels that each got.

#112 feat : 채팅방 관련 API 추가, 채팅 프론트 연결
  src/main/java/com/shineidle/tripf/chat/controller/ChatRoomController.java
  src/main/java/com/shineidle/tripf/chat/controller/ChatViewController.java
  src/main/java/com/shineidle/tripf/chat/dto/ChatMessageResponseDto.java
  src/main/java/com/shineidle/tripf/chat/service/ChatRoomService.java
  src/main/java/com/shineidle/tripf/chat/service/ChatRoomServiceImpl.java
  src/main/java/com/shineidle/tripf/common/exception/type/ChatErrorCode.java
  src/main/java/com/shineidle/tripf/common/message/enums/PostMessage.java
  src/main/resources/templates/chat/chat.html
Labels: 추가 기능, 프론트

#113 feat: 챗봇 기능 구현
  build.gradle
  src/main/java/com/shineidle/tripf/chatbot/RedisDataInitializer.java
  src/main/java/com/shineidle/tripf/chatbot/RedisService.java
  src/main/java/com/shineidle/tripf/chatbot/TrainDoccatModel.java
  src/main/java/com/shineidle/tripf/chatbot/controller/AdminChatbotController.java
  src/main/java/com/shineidle/tripf/chatbot/controller/ChatbotController.java
  src/main/java/com/shineidle/tripf/chatbot/dto/AdminChatbotAnswersResponseDto.java
  src/main/java/com/shineidle/tripf/chatbot/dto/AdminChatbotQuestionsRequestDto.java
  src/main/java/com/shineidle/tripf/chatbot/dto/ChatbotQuestionsResponseDto.java
  src/main/java/com/shineidle/tripf/chatbot/dto/ChatbotRequestDto.java
  src/main/java/com/shineidle/tripf/chatbot/dto/ChatbotResponseDto.java
  src/main/java/com/shineidle/tripf/chatbot/entity/Chatbot.java
  src/main/java/com/shineidle/tripf/chatbot/repository/ChatbotRepository.java
  src/main/java/com/shineidle/tripf/chatbot/service/ChatbotService.java
  src/main/java/com/shineidle/tripf/chatbot/service/ChatbotServiceImpl.java
  src/main/java/com/shineidle/tripf/chatbot/type/ResponseStatus.java
  src/main/java/com/shineidle/tripf/common/message/enums/PostMessage.java
  src/main/java/com/shineidle/tripf/config/WebConfig.java
  src/main/resources/models/doccat.bin
  src/main/resources/models/train.txt
Labels: 새로운 기능

#115 add : Test 코드 추가
  build.gradle
  src/main/java/com/shineidle/tripf/common/exception/GlobalExceptionHandler.java
  src/test/java/com/shineidle/tripf/cart/service/CartServiceImplTest.java
  src/test/java/com/shineidle/tripf/feed/service/FeedServiceImplTest.java
  src/test/java/com/shineidle/tripf/follow/service/FollowServiceImplTest.java
  src/test/java/com/shineidle/tripf/like/service/LikeServiceImplTest.java
  src/test/java/com/shineidle/tripf/notification/service/NotificationServiceImplTest.java
  src/test/java/com/shineidle/tripf/product/service/ProductServiceImplTest.java
  src/test/java/com/shineidle/tripf/user/service/UserServiceImplTest.java
  src/test/resources/application.yml
Labels: 테스트

#116 Feature/pay
  src/main/java/com/shineidle/tripf/common/exception/type/OrderErrorCode.java
  src/main/java/com/shineidle/tripf/order/dto/OrderRequestDto.java
  src/main/java/com/shineidle/tripf/order/dto/OrderResponseDto.java
  src/main/java/com/shineidle/tripf/order/entity/Order.java
  src/main/java/com/shineidle/tripf/order/repository/OrderRepository.java
  src/main/java/com/shineidle/tripf/order/service/OrderService.java
  src/main/java/com/shineidle/tripf/order/service/OrderServiceImpl.java
  src/main/java/com/shineidle/tripf/payment/config/PaymentConfig.java
  src/main/java/com/shineidle/tripf/payment/controller/PaymentController.java
  src/main/java/com/shineidle/tripf/payment/dto/ApiResponse.java
  src/main/java/com/shineidle/tripf/payment/dto/PaymentCancelDto.java
  src/main/java/com/shineidle/tripf/payment/dto/PaymentConfirmDto.java
  src/main/java/com/shineidle/tripf/payment/dto/PaymentDto.java
  src/main/java/com/shineidle/tripf/payment/dto/PaymentRequestDto.java
  src/main/java/com/shineidle/tripf/payment/entity/Payment.java
  src/main/java/com/shineidle/tripf/payment/repository/PaymentRepository.java
  src/main/java/com/shineidle/tripf/payment/service/PaymentService.java
  src/main/java/com/shineidle/tripf/payment/service/PaymentServiceImpl.java
  src/main/java/com/shineidle/tripf/payment/type/CancelStatus.java
  src/main/java/com/shineidle/tripf/payment/type/PaymentStatus.java
  src/main/resources/application.yml
  src/main/resources/static/tossPayment.html
  src/main/resources/templates/payment/cancel.html
  src/main/resources/templates/payment/cancelDetails.html
  src/main/resources/templates/payment/payConfirmation.html
  src/main/resources/templates/payment/payDetails.html
  src/main/resources/templates/payment/payRequest.html
Labels: 새로운 기능, 도움 요청, 추후 수행

#117 update : CI/CD 키값 추가 및 push 브랜치 변경
  .github/workflows/ec2-docker.yml
  src/main/java/com/shineidle/tripf/feed/controller/HomeViewController.java
  src/test/java/com/shineidle/tripf/TripfApplicationTests.java
Labels: CI/CD

#118 update : 유저 인증/인가 업데이트
  src/main/java/com/shineidle/tripf/config/WebConfig.java
  src/main/java/com/shineidle/tripf/feed/controller/FeedController.java
  src/main/java/com/shineidle/tripf/feed/controller/FeedViewController.java
  src/main/java/com/shineidle/tripf/feed/service/FeedService.java
  src/main/java/com/shineidle/tripf/feed/service/FeedServiceImpl.java
  src/main/java/com/shineidle/tripf/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/shineidle/tripf/user/service/UserServiceImpl.java
  src/main/resources/templates/feed/create.html
  src/main/resources/templates/fragments/header.html
Labels: 코드 수정, 핫픽스, 프론트

#119 fix : whiteList 수정
  src/main/java/com/shineidle/tripf/config/WebConfig.java
Labels: 코드 수정

#121 add : pay 기능 추가
  src/main/java/com/shineidle/tripf/config/WebConfig.java
  src/main/java/com/shineidle/tripf/paymentTest/controller/PaymentViewControllerTest.java
  src/main/java/com/shineidle/tripf/paymentTest/dto/PaymentConfirmRequestDtoTest.java
  src/main/java/com/shineidle/tripf/paymentTest/dto/PaymentRequestDtoTest.java
  src/main/java/com/shineidle/tripf/paymentTest/entity/PaymentTest.java
  src/main/java/com/shineidle/tripf/paymentTest/repository/PaymentRepositoryTest.java
  src/main/java/com/shineidle/tripf/paymentTest/service/PaymentServiceTest.java
  src/main/resources/application.yml
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/paymentTest/failTest.html
  src/main/resources/templates/paymentTest/paymentTest.html
  src/main/resources/templates/paymentTest/successTest.html
Labels: 코드 수정, 추가 기능

#124 mail 기능 업데이트
  src/main/java/com/shineidle/tripf/common/exception/type/MailErrorCode.java
  src/main/java/com/shineidle/tripf/config/WebConfig.java
  src/main/java/com/shineidle/tripf/mail/controller/MailController.java
  src/main/java/com/shineidle/tripf/mail/service/MailService.java
  src/main/java/com/shineidle/tripf/mail/service/MailServiceImpl.java
Labels: 리팩토링, 코드 수정, 추가 기능, 프론트

#126 feed 캐싱 적용
  src/main/java/com/shineidle/tripf/config/RedisConfig.java
  src/main/java/com/shineidle/tripf/feed/dto/DaysActivityDto.java
  src/main/java/com/shineidle/tripf/feed/repository/ActivityRepository.java
  src/main/java/com/shineidle/tripf/feed/repository/DaysRepository.java
  src/main/java/com/shineidle/tripf/feed/service/FeedServiceImpl.java
  src/main/java/com/shineidle/tripf/feed/service/RedisFeedService.java
Labels: 코드 수정, 추가 기능

#129 Refactor: payment 부분 리펙토링
  src/main/java/com/shineidle/tripf/order/dto/OrderRequestDto.java
  src/main/java/com/shineidle/tripf/order/dto/OrderResponseDto.java
  src/main/java/com/shineidle/tripf/order/entity/Order.java
  src/main/java/com/shineidle/tripf/order/repository/OrderRepository.java
  src/main/java/com/shineidle/tripf/order/service/OrderService.java
  src/main/java/com/shineidle/tripf/order/service/OrderServiceImpl.java
  src/main/java/com/shineidle/tripf/order/type/PayStatus.java
  src/main/java/com/shineidle/tripf/payment/config/PaymentConfig.java
  src/main/java/com/shineidle/tripf/payment/controller/PaymentController.java
  src/main/java/com/shineidle/tripf/payment/controller/PaymentViewController.java
  src/main/java/com/shineidle/tripf/payment/dto/ApiResponse.java
  src/main/java/com/shineidle/tripf/payment/dto/PaymentCancelDto.java
  src/main/java/com/shineidle/tripf/payment/dto/PaymentConfirmDto.java
  src/main/java/com/shineidle/tripf/payment/dto/PaymentConfirmRequestDto.java
  src/main/java/com/shineidle/tripf/payment/dto/PaymentDto.java
  src/main/java/com/shineidle/tripf/payment/dto/PaymentRequestDto.java
  src/main/java/com/shineidle/tripf/payment/entity/Payment.java
  src/main/java/com/shineidle/tripf/payment/repository/PaymentRepository.java
  src/main/java/com/shineidle/tripf/payment/service/PaymentService.java
  src/main/java/com/shineidle/tripf/payment/service/PaymentServiceImpl.java
  src/main/java/com/shineidle/tripf/payment/type/CancelStatus.java
  src/main/java/com/shineidle/tripf/payment/type/PaymentStatus.java
  src/main/java/com/shineidle/tripf/paymentTest/controller/PaymentViewControllerTest.java
  src/main/java/com/shineidle/tripf/paymentTest/dto/PaymentRequestDtoTest.java
  src/main/java/com/shineidle/tripf/paymentTest/entity/PaymentTest.java
  src/main/java/com/shineidle/tripf/paymentTest/repository/PaymentRepositoryTest.java
  src/main/java/com/shineidle/tripf/paymentTest/service/PaymentServiceTest.java
  src/main/resources/static/tossPayment.html
  src/main/resources/templates/payment/cancel.html
  src/main/resources/templates/payment/cancelDetails.html
  src/main/resources/templates/payment/fail.html
  src/main/resources/templates/payment/payConfirmation.html
  src/main/resources/templates/payment/payDetails.html
  src/main/resources/templates/payment/payRequest.html
  src/main/resources/templates/payment/payment.html
  src/main/resources/templates/payment/success.html
Labels: 코드 수정

#133 refactor : 코드 리팩토링
  src/main/java/com/shineidle/tripf/chat/controller/ChatController.java
  src/main/java/com/shineidle/tripf/chat/controller/ChatRoomController.java
  src/main/java/com/shineidle/tripf/chat/controller/ChatViewController.java
  src/main/java/com/shineidle/tripf/chat/dto/ChatMessageRequestDto.java
  src/main/java/com/shineidle/tripf/chat/dto/ChatRoomRequestDto.java
  src/main/java/com/shineidle/tripf/chat/entity/ChatMessage.java
  src/main/java/com/shineidle/tripf/chat/entity/ChatRoom.java
  src/main/java/com/shineidle/tripf/chat/repository/ChatMessageRepository.java
  src/main/java/com/shineidle/tripf/chat/repository/ChatRoomRepository.java
  src/main/java/com/shineidle/tripf/chat/service/ChatMessageService.java
  src/main/java/com/shineidle/tripf/chat/service/ChatMessageServiceImpl.java
  src/main/java/com/shineidle/tripf/chat/service/ChatRoomService.java
  src/main/java/com/shineidle/tripf/chat/service/ChatRoomServiceImpl.java
  src/main/java/com/shineidle/tripf/config/WebConfig.java
  src/main/java/com/shineidle/tripf/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/shineidle/tripf/oauth2/controller/OAuth2UnlinkController.java
  src/main/java/com/shineidle/tripf/oauth2/exception/OAuth2AuthenticationProcessingException.java
  src/main/java/com/shineidle/tripf/oauth2/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/shineidle/tripf/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/shineidle/tripf/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/shineidle/tripf/oauth2/service/OAuth2UserPrincipal.java
  src/main/java/com/shineidle/tripf/oauth2/user/OAuth2UserInfo.java
  src/main/java/com/shineidle/tripf/oauth2/user/OAuth2UserInfoFactory.java
  src/main/java/com/shineidle/tripf/oauth2/user/OAuth2UserUnlink.java
  src/main/java/com/shineidle/tripf/oauth2/user/OAuth2UserUnlinkManager.java
  src/main/java/com/shineidle/tripf/oauth2/user/RestTemplateFactory.java
  src/main/java/com/shineidle/tripf/oauth2/user/google/GoogleOAuth2UserInfo.java
  src/main/java/com/shineidle/tripf/oauth2/user/google/GoogleOAuth2UserUnlink.java
  src/main/java/com/shineidle/tripf/oauth2/user/kakao/KakaoOAuth2UserInfo.java
  src/main/java/com/shineidle/tripf/oauth2/user/kakao/KakaoOAuth2UserUnlink.java
  src/main/java/com/shineidle/tripf/oauth2/user/naver/NaverOAuth2UserInfo.java
  src/main/java/com/shineidle/tripf/oauth2/user/naver/NaverOAuth2UserUnlink.java
  src/main/java/com/shineidle/tripf/oauth2/util/CookieUtils.java
  src/main/java/com/shineidle/tripf/payment/service/PaymentService.java
  src/main/java/com/shineidle/tripf/product/controller/AdminProductController.java
  src/main/java/com/shineidle/tripf/product/controller/AdminProductViewController.java
  src/main/java/com/shineidle/tripf/product/controller/ProductController.java
  src/main/java/com/shineidle/tripf/product/controller/ProductViewController.java
  src/main/java/com/shineidle/tripf/product/entity/Product.java
  src/main/java/com/shineidle/tripf/product/service/ProductService.java
  src/main/java/com/shineidle/tripf/product/service/ProductServiceImpl.java
  src/main/java/com/shineidle/tripf/product/type/ProductStatus.java
  src/main/java/com/shineidle/tripf/user/controller/AccountViewController.java
  src/main/java/com/shineidle/tripf/user/controller/UserController.java
  src/main/java/com/shineidle/tripf/user/controller/UserViewController.java
  src/main/java/com/shineidle/tripf/user/entity/RefreshToken.java
  src/main/java/com/shineidle/tripf/user/entity/User.java
  src/main/java/com/shineidle/tripf/user/repository/RefreshTokenRepository.java
  src/main/java/com/shineidle/tripf/user/service/RefreshTokenService.java
  src/main/java/com/shineidle/tripf/user/service/RefreshTokenServiceImpl.java
  src/main/java/com/shineidle/tripf/user/service/UserService.java
  src/main/java/com/shineidle/tripf/user/service/UserServiceImpl.java
  src/main/java/com/shineidle/tripf/user/type/UserAuth.java
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/googleMap.html
  src/main/resources/templates/payment/payment.html
  src/main/resources/templates/payment/success.html
Labels: 리팩토링

#134 refactor : 코드 리팩토링
  src/main/java/com/shineidle/tripf/follow/controller/FollowController.java
  src/main/java/com/shineidle/tripf/follow/dto/FollowRequestDto.java
  src/main/java/com/shineidle/tripf/follow/entity/Follow.java
  src/main/java/com/shineidle/tripf/follow/repository/FollowRepository.java
  src/main/java/com/shineidle/tripf/follow/service/FollowService.java
  src/main/java/com/shineidle/tripf/follow/service/FollowServiceImpl.java
  src/main/java/com/shineidle/tripf/like/dto/FeedLikeDto.java
  src/main/java/com/shineidle/tripf/like/entity/Like.java
  src/main/java/com/shineidle/tripf/like/repository/LikeRepository.java
  src/main/java/com/shineidle/tripf/like/service/LikeService.java
  src/main/java/com/shineidle/tripf/order/controller/OrderController.java
  src/main/java/com/shineidle/tripf/order/entity/Order.java
  src/main/java/com/shineidle/tripf/order/repository/OrderRepository.java
  src/main/java/com/shineidle/tripf/order/service/OrderService.java
  src/main/java/com/shineidle/tripf/order/type/OrderStatus.java
  src/main/java/com/shineidle/tripf/orderProduct/controller/orderProductController.java
  src/main/java/com/shineidle/tripf/orderProduct/dto/OrderProductDto.java
  src/main/java/com/shineidle/tripf/orderProduct/dto/orderProductRequestDto.java
  src/main/java/com/shineidle/tripf/orderProduct/dto/orderProductResponseDto.java
  src/main/java/com/shineidle/tripf/orderProduct/entity/OrderProduct.java
  src/main/java/com/shineidle/tripf/orderProduct/repository/orderProductRepository.java
  src/main/java/com/shineidle/tripf/orderProduct/service/orderProductService.java
  src/main/java/com/shineidle/tripf/orderProduct/service/orderProductServiceImpl.java
Labels: 리팩토링

#135 Refactor: cart, photo, chatbot 코드 리펙토링
  src/main/java/com/shineidle/tripf/cart/controller/CartController.java
  src/main/java/com/shineidle/tripf/cart/controller/CartViewController.java
  src/main/java/com/shineidle/tripf/cart/dto/CartRequestDto.java
  src/main/java/com/shineidle/tripf/cart/dto/CartResponseDto.java
  src/main/java/com/shineidle/tripf/cart/entity/Cart.java
  src/main/java/com/shineidle/tripf/cart/repository/CartRepository.java
  src/main/java/com/shineidle/tripf/cart/service/CartService.java
  src/main/java/com/shineidle/tripf/cart/service/CartServiceImpl.java
  src/main/java/com/shineidle/tripf/chatbot/RedisChatbotService.java
  src/main/java/com/shineidle/tripf/chatbot/RedisDataInitializer.java
  src/main/java/com/shineidle/tripf/chatbot/TrainDoccatModel.java
  src/main/java/com/shineidle/tripf/chatbot/controller/AdminChatbotController.java
  src/main/java/com/shineidle/tripf/chatbot/controller/ChatbotController.java
  src/main/java/com/shineidle/tripf/chatbot/dto/AdminChatbotAnswersResponseDto.java
  src/main/java/com/shineidle/tripf/chatbot/dto/AdminChatbotQuestionsRequestDto.java
  src/main/java/com/shineidle/tripf/chatbot/dto/ChatbotQuestionsResponseDto.java
  src/main/java/com/shineidle/tripf/chatbot/dto/ChatbotRequestDto.java
  src/main/java/com/shineidle/tripf/chatbot/dto/ChatbotResponseDto.java
  src/main/java/com/shineidle/tripf/chatbot/entity/Chatbot.java
  src/main/java/com/shineidle/tripf/chatbot/repository/ChatbotRepository.java
  src/main/java/com/shineidle/tripf/chatbot/service/ChatbotService.java
  src/main/java/com/shineidle/tripf/chatbot/service/ChatbotServiceImpl.java
  src/main/java/com/shineidle/tripf/payment/dto/PaymentRequestDto.java
  src/main/java/com/shineidle/tripf/photo/controller/ActivityPhotoController.java
  src/main/java/com/shineidle/tripf/photo/controller/AdminProductPhotoController.java
  src/main/java/com/shineidle/tripf/photo/controller/ProductPhotoController.java
  src/main/java/com/shineidle/tripf/photo/dto/PhotoRequestDto.java
  src/main/java/com/shineidle/tripf/photo/dto/PhotoResponseDto.java
  src/main/java/com/shineidle/tripf/photo/entity/ActivityPhoto.java
  src/main/java/com/shineidle/tripf/photo/entity/Photo.java
  src/main/java/com/shineidle/tripf/photo/entity/ProductPhoto.java
  src/main/java/com/shineidle/tripf/photo/repository/ActivityPhotoRepository.java
  src/main/java/com/shineidle/tripf/photo/repository/PhotoRepository.java
  src/main/java/com/shineidle/tripf/photo/repository/ProductPhotoRepository.java
  src/main/java/com/shineidle/tripf/photo/service/PhotoService.java
  src/main/java/com/shineidle/tripf/photo/service/PhotoServiceImpl.java
  src/main/java/com/shineidle/tripf/photo/type/PhotoDomain.java
Labels: 리팩토링

#136 refactor : yml 환경 분리, 깃허브 액션 yml 수정, 빛나님 작성 코드 리팩토링
  .github/workflows/ec2-docker.yml
  src/main/java/com/shineidle/tripf/comment/controller/CommentController.java
  src/main/java/com/shineidle/tripf/comment/dto/CommentRequestDto.java
  src/main/java/com/shineidle/tripf/comment/dto/CommentResponseDto.java
  src/main/java/com/shineidle/tripf/comment/entity/Comment.java
  src/main/java/com/shineidle/tripf/comment/repository/CommentRepository.java
  src/main/java/com/shineidle/tripf/comment/service/CommentService.java
  src/main/java/com/shineidle/tripf/comment/service/CommentServiceImpl.java
  src/main/java/com/shineidle/tripf/feed/controller/FeedViewController.java
  src/main/java/com/shineidle/tripf/geo/dto/GeoResponseDto.java
  src/main/java/com/shineidle/tripf/geo/service/GeoService.java
  src/main/java/com/shineidle/tripf/geo/service/GeoServiceImpl.java
  src/main/java/com/shineidle/tripf/mail/controller/MailController.java
  src/main/java/com/shineidle/tripf/mail/service/MailService.java
  src/main/java/com/shineidle/tripf/mail/service/MailServiceImpl.java
  src/main/java/com/shineidle/tripf/notification/controller/NotificationController.java
  src/main/java/com/shineidle/tripf/notification/controller/NotificationViewController.java
  src/main/java/com/shineidle/tripf/notification/dto/NotificationRequestDto.java
  src/main/java/com/shineidle/tripf/notification/dto/NotificationResponseDto.java
  src/main/java/com/shineidle/tripf/notification/entity/Notification.java
  src/main/java/com/shineidle/tripf/notification/repository/NotificationRepository.java
  src/main/java/com/shineidle/tripf/notification/service/NotificationService.java
  src/main/java/com/shineidle/tripf/notification/service/NotificationServiceImpl.java
  src/main/resources/application-deploy.yml
  src/main/resources/application-develop.yml
  src/test/java/com/shineidle/tripf/feed/service/FeedServiceImplTest.java
Labels: 리팩토링

#138 refactor : 코드 리팩토링
  src/main/java/com/shineidle/tripf/cart/controller/CartController.java
  src/main/java/com/shineidle/tripf/cart/controller/CartViewController.java
  src/main/java/com/shineidle/tripf/cart/dto/CartRequestDto.java
  src/main/java/com/shineidle/tripf/cart/entity/Cart.java
  src/main/java/com/shineidle/tripf/cart/repository/CartRepository.java
  src/main/java/com/shineidle/tripf/cart/service/CartService.java
  src/main/java/com/shineidle/tripf/cart/service/CartServiceImpl.java
  src/main/java/com/shineidle/tripf/chatbot/RedisChatbotService.java
  src/main/java/com/shineidle/tripf/chatbot/RedisDataInitializer.java
  src/main/java/com/shineidle/tripf/chatbot/TrainDoccatModel.java
  src/main/java/com/shineidle/tripf/chatbot/controller/ChatbotController.java
  src/main/java/com/shineidle/tripf/chatbot/dto/ChatbotRequestDto.java
  src/main/java/com/shineidle/tripf/chatbot/dto/ChatbotResponseDto.java
  src/main/java/com/shineidle/tripf/chatbot/entity/Chatbot.java
  src/main/java/com/shineidle/tripf/chatbot/repository/ChatbotRepository.java
  src/main/java/com/shineidle/tripf/chatbot/service/ChatbotService.java
  src/main/java/com/shineidle/tripf/chatbot/service/ChatbotServiceImpl.java
  src/main/java/com/shineidle/tripf/photo/controller/ActivityPhotoController.java
  src/main/java/com/shineidle/tripf/photo/controller/AdminProductPhotoController.java
  src/main/java/com/shineidle/tripf/photo/controller/ProductPhotoController.java
  src/main/java/com/shineidle/tripf/photo/dto/PhotoRequestDto.java
  src/main/java/com/shineidle/tripf/photo/dto/PhotoResponseDto.java
  src/main/java/com/shineidle/tripf/photo/entity/ActivityPhoto.java
  src/main/java/com/shineidle/tripf/photo/entity/Photo.java
  src/main/java/com/shineidle/tripf/photo/entity/ProductPhoto.java
  src/main/java/com/shineidle/tripf/photo/repository/ActivityPhotoRepository.java
  src/main/java/com/shineidle/tripf/photo/repository/ProductPhotoRepository.java
  src/main/java/com/shineidle/tripf/photo/service/PhotoService.java
  src/main/java/com/shineidle/tripf/photo/service/PhotoServiceImpl.java
Labels: 리팩토링

#139 refactor : 코드 리팩토링 및 javadoc 추가, workflows yml 파일 수정
  .github/workflows/ec2-docker.yml
  src/main/java/com/shineidle/tripf/comment/repository/CommentRepository.java
  src/main/java/com/shineidle/tripf/feed/controller/FeedController.java
  src/main/java/com/shineidle/tripf/feed/controller/FeedViewController.java
  src/main/java/com/shineidle/tripf/feed/controller/HomeController.java
  src/main/java/com/shineidle/tripf/feed/controller/HomeViewController.java
  src/main/java/com/shineidle/tripf/feed/entity/Days.java
  src/main/java/com/shineidle/tripf/feed/entity/Feed.java
  src/main/java/com/shineidle/tripf/feed/service/FeedService.java
  src/main/java/com/shineidle/tripf/feed/service/FeedServiceImpl.java
  src/main/java/com/shineidle/tripf/feed/service/RedisFeedService.java
  src/main/java/com/shineidle/tripf/geo/service/GeoService.java
  src/main/java/com/shineidle/tripf/mail/controller/MailController.java
  src/main/java/com/shineidle/tripf/mail/service/MailService.java
  src/main/java/com/shineidle/tripf/mail/service/MailServiceImpl.java
  src/main/java/com/shineidle/tripf/notification/controller/NotificationViewController.java
  src/main/java/com/shineidle/tripf/notification/entity/Notification.java
  src/main/java/com/shineidle/tripf/notification/repository/NotificationRepository.java
Labels: 리팩토링

#140 OAuth2 부분 코드 리팩토링 및 javadoc 추가
  src/main/java/com/shineidle/tripf/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/shineidle/tripf/oauth2/controller/OAuth2UnlinkController.java
  src/main/java/com/shineidle/tripf/oauth2/exception/OAuth2AuthenticationProcessingException.java
  src/main/java/com/shineidle/tripf/oauth2/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/shineidle/tripf/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/shineidle/tripf/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/shineidle/tripf/oauth2/service/OAuth2UserPrincipal.java
  src/main/java/com/shineidle/tripf/oauth2/user/OAuth2UserInfo.java
  src/main/java/com/shineidle/tripf/oauth2/user/OAuth2UserInfoFactory.java
  src/main/java/com/shineidle/tripf/oauth2/user/OAuth2UserUnlink.java
  src/main/java/com/shineidle/tripf/oauth2/user/OAuth2UserUnlinkManager.java
  src/main/java/com/shineidle/tripf/oauth2/user/RestTemplateFactory.java
  src/main/java/com/shineidle/tripf/oauth2/user/google/GoogleOAuth2UserInfo.java
  src/main/java/com/shineidle/tripf/oauth2/user/google/GoogleOAuth2UserUnlink.java
  src/main/java/com/shineidle/tripf/oauth2/user/kakao/KakaoOAuth2UserInfo.java
  src/main/java/com/shineidle/tripf/oauth2/user/kakao/KakaoOAuth2UserUnlink.java
  src/main/java/com/shineidle/tripf/oauth2/user/naver/NaverOAuth2UserInfo.java
  src/main/java/com/shineidle/tripf/oauth2/user/naver/NaverOAuth2UserUnlink.java
  src/main/java/com/shineidle/tripf/oauth2/util/CookieUtils.java
Labels: 리팩토링

#143 refactor : 코드 리팩토링 및 javadoc 추가
  src/main/java/com/shineidle/tripf/chat/controller/ChatViewController.java
  src/main/java/com/shineidle/tripf/chat/repository/ChatMessageRepository.java
  src/main/java/com/shineidle/tripf/chat/repository/ChatRoomRepository.java
  src/main/java/com/shineidle/tripf/chat/service/ChatMessageService.java
  src/main/java/com/shineidle/tripf/chat/service/ChatMessageServiceImpl.java
  src/main/java/com/shineidle/tripf/chat/service/ChatRoomService.java
  src/main/java/com/shineidle/tripf/chat/service/ChatRoomServiceImpl.java
  src/main/java/com/shineidle/tripf/common/util/JwtProvider.java
  src/main/java/com/shineidle/tripf/common/util/chat/StompHandler.java
  src/main/java/com/shineidle/tripf/common/util/chat/WebSocketSessionManager.java
  src/main/java/com/shineidle/tripf/config/RedisConfig.java
  src/main/java/com/shineidle/tripf/config/S3Config.java
  src/main/java/com/shineidle/tripf/config/WebSocketConfig.java
  src/main/java/com/shineidle/tripf/config/interceptor/JwtHandshakeInterceptor.java
  src/main/java/com/shineidle/tripf/product/service/ProductService.java
  src/main/java/com/shineidle/tripf/user/controller/AccountViewController.java
  src/main/java/com/shineidle/tripf/user/controller/UserViewController.java
  src/main/java/com/shineidle/tripf/user/repository/RefreshTokenRepository.java
  src/main/java/com/shineidle/tripf/user/service/RefreshTokenService.java
  src/main/java/com/shineidle/tripf/user/service/UserService.java
  src/main/java/com/shineidle/tripf/user/type/UserAuth.java
Labels: 리팩토링, 코드 수정

#141 Refactor: 코드 리펙토링
  src/main/java/com/shineidle/tripf/follow/controller/FollowController.java
  src/main/java/com/shineidle/tripf/follow/dto/FollowRequestDto.java
  src/main/java/com/shineidle/tripf/follow/dto/FollowResponseDto.java
  src/main/java/com/shineidle/tripf/follow/entity/Follow.java
  src/main/java/com/shineidle/tripf/follow/entity/FollowPk.java
  src/main/java/com/shineidle/tripf/follow/repository/FollowRepository.java
  src/main/java/com/shineidle/tripf/like/controller/LikeController.java
  src/main/java/com/shineidle/tripf/like/dto/FeedLikeDto.java
  src/main/java/com/shineidle/tripf/like/entity/LikePk.java
  src/main/java/com/shineidle/tripf/like/repository/LikeRepository.java
  src/main/java/com/shineidle/tripf/order/controller/OrderController.java
  src/main/java/com/shineidle/tripf/order/repository/OrderRepository.java
  src/main/java/com/shineidle/tripf/orderProduct/entity/OrderProduct.java
  src/main/java/com/shineidle/tripf/payment/controller/PaymentViewController.java
  src/main/java/com/shineidle/tripf/payment/entity/Payment.java
  src/main/java/com/shineidle/tripf/payment/service/PaymentService.java
Labels: 리팩토링

#145 fix : import문 수정, LikeRepository JPQL 수정
  src/main/java/com/shineidle/tripf/domain/feed/controller/FeedController.java
  src/main/java/com/shineidle/tripf/domain/feed/controller/FeedViewController.java
  src/main/java/com/shineidle/tripf/domain/feed/service/FeedService.java
  src/main/java/com/shineidle/tripf/domain/feed/service/FeedServiceImpl.java
  src/main/java/com/shineidle/tripf/domain/like/repository/LikeRepository.java
  src/main/java/com/shineidle/tripf/domain/user/service/UserService.java
  src/main/java/com/shineidle/tripf/domain/user/service/UserServiceImpl.java
Labels: 코드 수정

#146 refactor : 커스텀 예외처리 추가, 웹소켓 엔드포인트 변경
  src/main/java/com/shineidle/tripf/domain/user/controller/AccountViewController.java
  src/main/java/com/shineidle/tripf/domain/user/type/UserAuth.java
  src/main/java/com/shineidle/tripf/global/common/exception/type/CommonErrorCode.java
  src/main/java/com/shineidle/tripf/global/common/exception/type/UserErrorCode.java
  src/main/java/com/shineidle/tripf/global/security/oauth2/user/OAuth2UserInfo.java
  src/main/java/com/shineidle/tripf/global/security/oauth2/user/naver/NaverOAuth2UserUnlink.java
  src/main/java/com/shineidle/tripf/global/security/oauth2/util/CookieUtils.java
  src/main/resources/static/js/app.js
Labels: 리팩토링, 코드 수정

#150 코드 리팩토링
  .github/workflows/ec2-docker.yml
  src/main/java/com/shineidle/tripf/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/shineidle/tripf/domain/feed/controller/HomeViewController.java
  src/main/java/com/shineidle/tripf/domain/feed/service/FeedServiceImpl.java
  src/main/java/com/shineidle/tripf/domain/mail/controller/MailController.java
  src/main/java/com/shineidle/tripf/domain/mail/service/MailService.java
  src/main/java/com/shineidle/tripf/domain/mail/service/MailServiceImpl.java
  src/main/java/com/shineidle/tripf/domain/payment/controller/PaymentViewController.java
  src/main/java/com/shineidle/tripf/domain/payment/entity/Payment.java
  src/main/java/com/shineidle/tripf/domain/payment/repository/PaymentRepository.java
  src/main/java/com/shineidle/tripf/domain/payment/service/PaymentService.java
  src/main/java/com/shineidle/tripf/domain/payment/service/PaymentServiceImpl.java
  src/main/java/com/shineidle/tripf/global/config/RedisConfig.java
Labels: 리팩토링

#147 fix: follow 코드 수정
  src/main/java/com/shineidle/tripf/domain/follow/service/FollowService.java
  src/main/java/com/shineidle/tripf/domain/follow/service/FollowServiceImpl.java
Labels: 코드 수정

#149 refactor : 코드 리팩토링
  src/main/java/com/shineidle/tripf/domain/cart/service/CartService.java
  src/main/java/com/shineidle/tripf/domain/cart/service/CartServiceImpl.java
  src/main/java/com/shineidle/tripf/domain/chatbot/model/TrainDoccatModel.java
  src/main/java/com/shineidle/tripf/domain/chatbot/service/ChatbotService.java
  src/main/java/com/shineidle/tripf/domain/chatbot/service/ChatbotServiceImpl.java
  src/main/java/com/shineidle/tripf/domain/photo/controller/ActivityPhotoController.java
  src/main/java/com/shineidle/tripf/domain/photo/controller/AdminProductPhotoController.java
  src/main/java/com/shineidle/tripf/domain/photo/dto/PhotoResponseDto.java
  src/main/java/com/shineidle/tripf/domain/photo/service/PhotoService.java
  src/main/java/com/shineidle/tripf/domain/photo/service/PhotoServiceImpl.java
Labels: 리팩토링

#152 test : feed test 코드 작성
  src/test/java/com/shineidle/tripf/cart/service/CartServiceImplTest.java
  src/test/java/com/shineidle/tripf/domain/chat/service/ChatMessageServiceImplTest.java
  src/test/java/com/shineidle/tripf/domain/chat/service/ChatRoomServiceImplTest.java
  src/test/java/com/shineidle/tripf/domain/feed/controller/FeedControllerTest.java
  src/test/java/com/shineidle/tripf/domain/feed/repository/FeedRepositoryTest.java
  src/test/java/com/shineidle/tripf/domain/feed/service/FeedServiceImplTest.java
  src/test/java/com/shineidle/tripf/domain/product/repository/ProductRepositoryTest.java
  src/test/java/com/shineidle/tripf/domain/product/service/ProductServiceImplTest.java
  src/test/java/com/shineidle/tripf/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/shineidle/tripf/domain/user/service/UserServiceImplTest.java
  src/test/java/com/shineidle/tripf/feed/service/FeedServiceImplTest.java
Labels: 테스트

#153 test: follow test 코드 작성
  src/main/java/com/shineidle/tripf/domain/follow/service/FollowServiceImpl.java
  src/test/java/com/shineidle/tripf/follow/controller/FollowControllerTest.java
  src/test/java/com/shineidle/tripf/follow/repository/FollowRepositoryTest.java
  src/test/java/com/shineidle/tripf/follow/service/FollowServiceImplTest.java
Labels: 테스트

#154 move : CartServiceImplTest, LikeServiceImplTest, NotificationServiceImplTest 패키지 이동
  src/test/java/com/shineidle/tripf/domain/cart/service/CartServiceImplTest.java
  src/test/java/com/shineidle/tripf/domain/like/service/LikeServiceImplTest.java
  src/test/java/com/shineidle/tripf/domain/notification/service/NotificationServiceImplTest.java
Labels: 테스트

#156 test: cart 및 chatbot test 코드 작성
  src/main/java/com/shineidle/tripf/domain/cart/dto/CartResponseDto.java
  src/main/java/com/shineidle/tripf/domain/cart/service/CartServiceImpl.java
  src/main/java/com/shineidle/tripf/domain/product/entity/Product.java
  src/main/java/com/shineidle/tripf/domain/user/entity/User.java
  src/test/java/com/shineidle/tripf/domain/cart/controller/CartControllerTest.java
  src/test/java/com/shineidle/tripf/domain/cart/repository/CartRepositoryTest.java
  src/test/java/com/shineidle/tripf/domain/chatbot/repository/ChatbotRepositoryTest.java
Labels: 테스트

#157 bugfix : 피드작성 후 잘못된 캐싱데이터 지우고 있던 문제 해결
  src/main/java/com/shineidle/tripf/domain/feed/service/FeedServiceImpl.java
Labels: 버그, 코드 수정

#158 test : 피드 수정 후 Test가 통과되지 않는 문제 해결
  src/test/java/com/shineidle/tripf/domain/feed/service/FeedServiceImplTest.java
Labels: 버그, 코드 수정, 테스트

#159 docs : 리드미 내용 수정
  README.md
Labels: 문서

#161 fix : null 값으로 인해 결제가 성공적으로 처리되지 않던 문제 해결
  src/main/java/com/shineidle/tripf/domain/payment/entity/Payment.java
  src/main/java/com/shineidle/tripf/domain/payment/service/PaymentServiceImpl.java
Labels: 버그, 코드 수정

#160 Update README.md
  README.md
Labels: 문서

#167 refactor : Feed 단일책임원칙 적용
  src/main/java/com/shineidle/tripf/domain/feed/dto/FeedRequestDto.java
  src/main/java/com/shineidle/tripf/domain/feed/service/FeedServiceImpl.java
Labels: 리팩토링

#168 refactor : 인증/인가 리팩토링 및 RefreshToken DB -> Redis 캐싱 방식으로 변경
  src/main/java/com/shineidle/tripf/domain/feed/controller/HomeViewController.java
  src/main/java/com/shineidle/tripf/domain/user/controller/AccountController.java
  src/main/java/com/shineidle/tripf/domain/user/service/RefreshTokenService.java
  src/main/java/com/shineidle/tripf/domain/user/service/RefreshTokenServiceImpl.java
  src/main/java/com/shineidle/tripf/domain/user/service/UserService.java
  src/main/java/com/shineidle/tripf/domain/user/service/UserServiceImpl.java
  src/main/java/com/shineidle/tripf/global/common/util/provider/JwtProvider.java
  src/main/java/com/shineidle/tripf/global/security/filter/JwtAuthFilter.java
  src/main/java/com/shineidle/tripf/global/security/interceptor/JwtHandshakeInterceptor.java
  src/main/java/com/shineidle/tripf/global/security/oauth2/controller/OAuth2UnlinkController.java
Labels: 리팩토링

#170 refactor : Feed RedisLock 어노테이션 기반 AOP 적용
  src/main/java/com/shineidle/tripf/domain/feed/service/FeedServiceImpl.java
  src/main/java/com/shineidle/tripf/global/common/util/redis/RedisLock.java
  src/main/java/com/shineidle/tripf/global/common/util/redis/RedisLockAspect.java
Labels: 리팩토링, 코드 수정

#171 feat: chatbot 프론트 생성
  src/main/java/com/shineidle/tripf/domain/chatbot/controller/ChatbotViewController.java
  src/main/resources/templates/chatbot/admin.html
  src/main/resources/templates/chatbot/chat.html
Labels: 프론트
